import { Header } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import { ReactNode } from 'react';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Gia Sư Poly',
  description: 'Generated by create next app',
};
interface Props {
  children: ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/*<Providers>*/}
        <Header />
        <div className={'mt-[100px] md:mt-[67px]'}>{props.children}</div>
        <Footer />
        {/*</Providers>*/}
      </body>
    </html>
  );
}
