import './globals.css';
import type { Metadata } from 'next';
import { Inter, Poppins } from 'next/font/google';
import { Header, Navigation } from '@/components';
const poppins = Poppins({ weight: ['500'], subsets: ['latin'] });
const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Gia Sư Poly',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className={'flex mt-[81px]'}>
          <Navigation />
          <main className={'max-w-[1280px] mx-auto py-5'}>{children}</main>
        </div>
      </body>
    </html>
  );
}
