import { Header } from '@/components';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import { ReactNode } from 'react';
import { GlobalContextProvider } from '@/contexts';
import Layout from '@/components/Layout';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Gia Sư Poly',
  description: 'Generated by create next app',
};
interface Props {
  children: ReactNode;
}

export default function RootLayout(props: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GlobalContextProvider store={[]}>
          <Layout>
            <div className={'mt-[67px] min-h-content'}>{props.children}</div>
          </Layout>
        </GlobalContextProvider>
      </body>
    </html>
  );
}
